apiVersion: fadk8sctrl.fortinet.com/v1alpha2
kind: FortiADCGatewayParameter
metadata:
  name: my-fadc-params
  namespace: gateway-system
spec:
  # Required fields
  managementIP: "172.23.133.110"       # Replace with your actual FortiADC management IP
  managementPort: 443                # Default is 443
  credentialsSecretRef: "fad-login"  # Name of the Secret storing login credentials
  virtualDomain: "root"

